# View
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_iOScalculator(object):
    def setupUi(self, iOScalculator):
        iOScalculator.setObjectName("iOScalculator")
        iOScalculator.resize(325, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(iOScalculator.sizePolicy().hasHeightForWidth())
        iOScalculator.setSizePolicy(sizePolicy)
        iOScalculator.setMinimumSize(QtCore.QSize(325, 600))
        iOScalculator.setMaximumSize(QtCore.QSize(325, 600))
        self.centralwidget = QtWidgets.QWidget(parent=iOScalculator)
        self.centralwidget.setObjectName("centralwidget")
        self.calculator_textBrowser = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.calculator_textBrowser.setGeometry(QtCore.QRect(10, 10, 300, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculator_textBrowser.sizePolicy().hasHeightForWidth())
        self.calculator_textBrowser.setSizePolicy(sizePolicy)
        self.calculator_textBrowser.setMinimumSize(QtCore.QSize(300, 150))
        self.calculator_textBrowser.setMaximumSize(QtCore.QSize(300, 150))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(72)
        self.calculator_textBrowser.setFont(font)
        self.calculator_textBrowser.setObjectName("calculator_textBrowser")
        self.pushButton9 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton9.setGeometry(QtCore.QRect(160, 220, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton9.sizePolicy().hasHeightForWidth())
        self.pushButton9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton9.setFont(font)
        self.pushButton9.setObjectName("pushButton9")
        self.pushButton8 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton8.setGeometry(QtCore.QRect(85, 220, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton8.sizePolicy().hasHeightForWidth())
        self.pushButton8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton8.setFont(font)
        self.pushButton8.setObjectName("pushButton8")
        self.pushButton7 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton7.setGeometry(QtCore.QRect(10, 220, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton7.sizePolicy().hasHeightForWidth())
        self.pushButton7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton7.setFont(font)
        self.pushButton7.setObjectName("pushButton7")
        self.pushButtonClear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonClear.setGeometry(QtCore.QRect(10, 170, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonClear.sizePolicy().hasHeightForWidth())
        self.pushButtonClear.setSizePolicy(sizePolicy)
        self.pushButtonClear.setMinimumSize(QtCore.QSize(75, 50))
        self.pushButtonClear.setMaximumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonClear.setFont(font)
        self.pushButtonClear.setObjectName("pushButtonClear")
        self.pushButtonDelete = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDelete.setGeometry(QtCore.QRect(85, 170, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDelete.sizePolicy().hasHeightForWidth())
        self.pushButtonDelete.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonDelete.setFont(font)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.pushButtonPosNeg = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonPosNeg.setGeometry(QtCore.QRect(160, 170, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPosNeg.sizePolicy().hasHeightForWidth())
        self.pushButtonPosNeg.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonPosNeg.setFont(font)
        self.pushButtonPosNeg.setObjectName("pushButtonPosNeg")
        self.pushButtonDiv = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDiv.setGeometry(QtCore.QRect(235, 170, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDiv.sizePolicy().hasHeightForWidth())
        self.pushButtonDiv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonDiv.setFont(font)
        self.pushButtonDiv.setObjectName("pushButtonDiv")
        self.pushButtonMult = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMult.setGeometry(QtCore.QRect(235, 220, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMult.sizePolicy().hasHeightForWidth())
        self.pushButtonMult.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonMult.setFont(font)
        self.pushButtonMult.setObjectName("pushButtonMult")
        self.pushButtonSub = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonSub.setGeometry(QtCore.QRect(235, 270, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonSub.sizePolicy().hasHeightForWidth())
        self.pushButtonSub.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonSub.setFont(font)
        self.pushButtonSub.setObjectName("pushButtonSub")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonAdd.setGeometry(QtCore.QRect(235, 320, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonAdd.setFont(font)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.pushButtonEquals = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonEquals.setGeometry(QtCore.QRect(235, 370, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonEquals.sizePolicy().hasHeightForWidth())
        self.pushButtonEquals.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonEquals.setFont(font)
        self.pushButtonEquals.setObjectName("pushButtonEquals")
        self.pushButton6 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton6.setGeometry(QtCore.QRect(160, 270, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton6.sizePolicy().hasHeightForWidth())
        self.pushButton6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton6.setFont(font)
        self.pushButton6.setObjectName("pushButton6")
        self.pushButton5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton5.setGeometry(QtCore.QRect(85, 270, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton5.sizePolicy().hasHeightForWidth())
        self.pushButton5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton5.setFont(font)
        self.pushButton5.setObjectName("pushButton5")
        self.pushButton4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton4.setGeometry(QtCore.QRect(10, 270, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton4.sizePolicy().hasHeightForWidth())
        self.pushButton4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton4.setFont(font)
        self.pushButton4.setObjectName("pushButton4")
        self.pushButton1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(10, 320, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton1.sizePolicy().hasHeightForWidth())
        self.pushButton1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton1.setFont(font)
        self.pushButton1.setObjectName("pushButton1")
        self.pushButton2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(85, 320, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton2.sizePolicy().hasHeightForWidth())
        self.pushButton2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton2.setFont(font)
        self.pushButton2.setObjectName("pushButton2")
        self.pushButton3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton3.setGeometry(QtCore.QRect(160, 320, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton3.sizePolicy().hasHeightForWidth())
        self.pushButton3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton3.setFont(font)
        self.pushButton3.setObjectName("pushButton3")
        self.pushButtonDec = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonDec.setGeometry(QtCore.QRect(160, 370, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonDec.sizePolicy().hasHeightForWidth())
        self.pushButtonDec.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonDec.setFont(font)
        self.pushButtonDec.setObjectName("pushButtonDec")
        self.pushButton0 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton0.setGeometry(QtCore.QRect(85, 370, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton0.sizePolicy().hasHeightForWidth())
        self.pushButton0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButton0.setFont(font)
        self.pushButton0.setObjectName("pushButton0")
        self.pushButtonMode = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonMode.setGeometry(QtCore.QRect(10, 370, 75, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonMode.sizePolicy().hasHeightForWidth())
        self.pushButtonMode.setSizePolicy(sizePolicy)
        self.pushButtonMode.setMinimumSize(QtCore.QSize(75, 50))
        self.pushButtonMode.setMaximumSize(QtCore.QSize(75, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.pushButtonMode.setFont(font)
        self.pushButtonMode.setObjectName("pushButtonMode")
        self.radioButtonSqr = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonSqr.setGeometry(QtCore.QRect(40, 450, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonSqr.sizePolicy().hasHeightForWidth())
        self.radioButtonSqr.setSizePolicy(sizePolicy)
        self.radioButtonSqr.setMinimumSize(QtCore.QSize(100, 25))
        self.radioButtonSqr.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.radioButtonSqr.setFont(font)
        self.radioButtonSqr.setObjectName("radioButtonSqr")
        self.radioButtonCir = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonCir.setGeometry(QtCore.QRect(40, 480, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonCir.sizePolicy().hasHeightForWidth())
        self.radioButtonCir.setSizePolicy(sizePolicy)
        self.radioButtonCir.setMinimumSize(QtCore.QSize(100, 25))
        self.radioButtonCir.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.radioButtonCir.setFont(font)
        self.radioButtonCir.setObjectName("radioButtonCir")
        self.radioButtonTri = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonTri.setGeometry(QtCore.QRect(180, 480, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonTri.sizePolicy().hasHeightForWidth())
        self.radioButtonTri.setSizePolicy(sizePolicy)
        self.radioButtonTri.setMinimumSize(QtCore.QSize(100, 25))
        self.radioButtonTri.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.radioButtonTri.setFont(font)
        self.radioButtonTri.setObjectName("radioButtonTri")
        self.radioButtonRec = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radioButtonRec.setGeometry(QtCore.QRect(180, 450, 100, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonRec.sizePolicy().hasHeightForWidth())
        self.radioButtonRec.setSizePolicy(sizePolicy)
        self.radioButtonRec.setMinimumSize(QtCore.QSize(100, 25))
        self.radioButtonRec.setMaximumSize(QtCore.QSize(100, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        self.radioButtonRec.setFont(font)
        self.radioButtonRec.setObjectName("radioButtonRec")
        self.label_AreaCalc = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_AreaCalc.setGeometry(QtCore.QRect(90, 420, 135, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_AreaCalc.sizePolicy().hasHeightForWidth())
        self.label_AreaCalc.setSizePolicy(sizePolicy)
        self.label_AreaCalc.setMinimumSize(QtCore.QSize(135, 25))
        self.label_AreaCalc.setMaximumSize(QtCore.QSize(135, 25))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_AreaCalc.setFont(font)
        self.label_AreaCalc.setObjectName("label_AreaCalc")
        self.textBrowserAreaGuide = QtWidgets.QTextBrowser(parent=self.centralwidget)
        self.textBrowserAreaGuide.setGeometry(QtCore.QRect(30, 510, 256, 41))
        self.textBrowserAreaGuide.setObjectName("textBrowserAreaGuide")
        iOScalculator.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=iOScalculator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 325, 22))
        self.menubar.setObjectName("menubar")
        iOScalculator.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=iOScalculator)
        self.statusbar.setObjectName("statusbar")
        iOScalculator.setStatusBar(self.statusbar)

        self.retranslateUi(iOScalculator)
        QtCore.QMetaObject.connectSlotsByName(iOScalculator)

    def retranslateUi(self, iOScalculator):
        _translate = QtCore.QCoreApplication.translate
        iOScalculator.setWindowTitle(_translate("iOScalculator", "iOScalc"))
        self.calculator_textBrowser.setHtml(_translate("iOScalculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Times New Roman\'; font-size:72pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.pushButton9.setText(_translate("iOScalculator", "9"))
        self.pushButton8.setText(_translate("iOScalculator", "8"))
        self.pushButton7.setText(_translate("iOScalculator", "7"))
        self.pushButtonClear.setText(_translate("iOScalculator", "Clear"))
        self.pushButtonDelete.setText(_translate("iOScalculator", "Del"))
        self.pushButtonPosNeg.setText(_translate("iOScalculator", "+/-"))
        self.pushButtonDiv.setText(_translate("iOScalculator", "/"))
        self.pushButtonMult.setText(_translate("iOScalculator", "*"))
        self.pushButtonSub.setText(_translate("iOScalculator", "-"))
        self.pushButtonAdd.setText(_translate("iOScalculator", "+"))
        self.pushButtonEquals.setText(_translate("iOScalculator", "="))
        self.pushButton6.setText(_translate("iOScalculator", "6"))
        self.pushButton5.setText(_translate("iOScalculator", "5"))
        self.pushButton4.setText(_translate("iOScalculator", "4"))
        self.pushButton1.setText(_translate("iOScalculator", "1"))
        self.pushButton2.setText(_translate("iOScalculator", "2"))
        self.pushButton3.setText(_translate("iOScalculator", "3"))
        self.pushButtonDec.setText(_translate("iOScalculator", "."))
        self.pushButton0.setText(_translate("iOScalculator", "0"))
        self.pushButtonMode.setText(_translate("iOScalculator", "Mode"))
        self.radioButtonSqr.setText(_translate("iOScalculator", "Square"))
        self.radioButtonCir.setText(_translate("iOScalculator", "Circle"))
        self.radioButtonTri.setText(_translate("iOScalculator", "Triangle"))
        self.radioButtonRec.setText(_translate("iOScalculator", "Rectangle"))
        self.label_AreaCalc.setText(_translate("iOScalculator", "Area calculator"))
        self.textBrowserAreaGuide.setHtml(_translate("iOScalculator", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.875pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
